[[presets]]
name = "ü©∑"
default = true
pixels = [
    [
        247,
        0,
        162,
        0.8,
    ],
    [
        247,
        0,
        162,
        0.8,
    ],
    [
        247,
        0,
        162,
        0.8,
    ],
    [
        247,
        0,
        162,
        0.8,
    ],
    [
        247,
        0,
        162,
        0.8,
    ],
    [
        247,
        0,
        162,
        0.8,
    ],
    [
        247,
        0,
        162,
        0.8,
    ],
    [
        247,
        0,
        162,
        0.8,
    ],
]

[[presets]]
name = "üéâ"
default = true
pixels = [
    [
        255,
        0,
        0,
        0.1,
    ],
    [
        255,
        0,
        0,
        0.1,
    ],
    [
        255,
        0,
        0,
        0.1,
    ],
    [
        255,
        0,
        0,
        0.1,
    ],
    [
        255,
        0,
        0,
        0.1,
    ],
    [
        255,
        0,
        0,
        0.1,
    ],
    [
        255,
        0,
        0,
        0.1,
    ],
    [
        255,
        0,
        0,
        0.1,
    ],
]

[[presets]]
name = "üôÇ"
default = true
pixels = [
    [
        0,
        150,
        14,
        0.1,
    ],
    [
        0,
        150,
        14,
        0.1,
    ],
    [
        0,
        150,
        14,
        0.1,
    ],
    [
        0,
        150,
        14,
        0.1,
    ],
    [
        0,
        150,
        14,
        0.1,
    ],
    [
        0,
        150,
        14,
        0.1,
    ],
    [
        0,
        150,
        14,
        0.1,
    ],
    [
        0,
        150,
        14,
        0.1,
    ],
]

[[presets]]
name = "ü´Ç"
default = true
pixels = [
    [
        4,
        50,
        255,
        0.1,
    ],
    [
        0,
        150,
        255,
        0.3,
    ],
    [
        0,
        252,
        255,
        0.2,
    ],
    [
        117,
        213,
        255,
        0.1,
    ],
    [
        117,
        213,
        255,
        0.1,
    ],
    [
        0,
        252,
        255,
        0.2,
    ],
    [
        0,
        150,
        255,
        0.3,
    ],
    [
        4,
        50,
        255,
        0.1,
    ],
]

[[presets]]
name = "üåà"
default = true
pixels = [
    [
        255,
        0,
        0,
        0.1,
    ],
    [
        255,
        38,
        0,
        0.1,
    ],
    [
        255,
        146,
        0,
        0.1,
    ],
    [
        254,
        251,
        0,
        0.1,
    ],
    [
        0,
        249,
        0,
        0.1,
    ],
    [
        4,
        50,
        255,
        0.1,
    ],
    [
        147,
        32,
        146,
        0.1,
    ],
    [
        255,
        64,
        255,
        0.1,
    ],
]

[[presets]]
name = "üç∞"
default = true
pixels = [
    [
        255,
        0,
        0,
        0.1,
    ],
    [
        234,
        234,
        234,
        0.1,
    ],
    [
        247,
        206,
        70,
        0.1,
    ],
    [
        247,
        206,
        70,
        0.1,
    ],
    [
        234,
        234,
        234,
        0.1,
    ],
    [
        234,
        234,
        234,
        0.1,
    ],
    [
        247,
        206,
        70,
        0.1,
    ],
    [
        247,
        206,
        70,
        0.1,
    ],
]
